[project]
name = "dbt-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "mypy>=1.15.0",
    "pydantic>=2.10.6",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "ruff>=0.9.9",
    "sgqlc>=16.4",
    "types-pyyaml>=6.0.12.20241230",
]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # Will enable this once all code is fully typed
disallow_incomplete_defs = false  # Will enable this once all code is fully typed
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
implicit_reexport = true
disable_error_code = [
    "method-assign", 
    "union-attr",
    "arg-type",
    "assignment",  
]

# Use explicit package bases
explicit_package_bases = true

# Ignore errors related to external libraries without type stubs
[[tool.mypy.overrides]]
module = [
    "sgqlc.*",
]
ignore_missing_imports = true

# Ignore errors in auto-generated schema file
[[tool.mypy.overrides]]
module = [
    "src.schema.schema",
]
ignore_errors = true

# Ignore errors in models.py related to Pydantic v2 model_config
[[tool.mypy.overrides]]
module = [
    "src.discovery_api.models",
]
disable_error_code = ["assignment"]
